name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libbsd-dev
      run: sudo apt-get install libbsd-dev -y
    - name: Compile the executable
      run: make
