name: Build

on:
  push:
    branches: [ main, 27-fix-the-build-pipeline ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libbsd-dev
      run: sudo apt-get install libbsd-dev -y
    - name: Cache build files
      uses: actions/cache@v3
      with:
        path: |
          build
          libraries/libft/build
          libraries/get_next_line/build
          libraries/mlx/*.o
        key: objs-${{ github.ref_name }}
        restore-keys: |
          objs-
    - name: make
      run: make
