name: Build

on:
  push:
    branches: [ main, 27-fix-the-build-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libbsd-dev
      run: sudo apt-get install libbsd-dev -y
    - name: Cache build files
      uses: actions/cache@v3
      with:
        path: "**/*.o"
        key: objs-${{ env.GITHUB_HEAD_REF }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          objs-${{ GITHUB_HEAD_REF }}-
          objs-
    - name: make
      run: make
